"use client";

import { ChangeEvent, useMemo, useState } from "react";

type StatsResponse = {
  total: number;
  counts: {
    Instrument: number;
    Equipment: number;
    "Pipe-run": number;
  };
  by_pid?: Array<{
    pid: string;
    total: number;
    counts: {
      Instrument: number;
      Equipment: number;
      "Pipe-run": number;
    };
  }>;
};

export default function StatisticsPage() {
  const [excelFile, setExcelFile] = useState<File | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [stats, setStats] = useState<StatsResponse | null>(null);

  const handleExcelSelection = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0] ?? null;
    setExcelFile(file);
    setError(null);
    setStats(null);
  };

  const handleAnalyze = async () => {
    if (!excelFile) {
      setError("Please choose an Excel file first.");
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const formData = new FormData();
      formData.append("excelFile", excelFile);

      const response = await fetch("/api/statistics", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to analyze the Excel file.");
      }

      setStats(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to analyze the Excel file.");
    } finally {
      setIsLoading(false);
    }
  };

  const chartData = useMemo(() => {
    if (!stats) return [];

    return [
      { label: "Instruments", value: stats.counts.Instrument, color: "#22c55e" },
      { label: "Equipment", value: stats.counts.Equipment, color: "#38bdf8" },
      { label: "Pipe-runs", value: stats.counts["Pipe-run"], color: "#a78bfa" },
    ];
  }, [stats]);

  const maxValue = Math.max(1, ...chartData.map((item) => item.value));

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-10 text-slate-100 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-5xl rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-2xl shadow-black/20">
        <div className="max-w-2xl">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.3em] text-cyan-400">
            Statistics
          </p>
          <h1 className="text-3xl font-semibold sm:text-4xl">
            Analyze the exported capture workbook
          </h1>
          <p className="mt-4 text-base leading-7 text-slate-400">
            Upload the Excel file generated by the capture workflow to view a chart of instrument, equipment, and pipe-run counts.
          </p>
        </div>

        <div className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="rounded-3xl border border-slate-800 bg-slate-950/70 p-6">
            <label className="flex cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-slate-700 bg-slate-900/70 px-6 py-10 text-center transition hover:border-cyan-400 hover:bg-slate-900">
              <input
                type="file"
                className="sr-only"
                onChange={handleExcelSelection}
                accept=".xlsx,.xls,.csv"
              />
              <span className="text-lg font-medium text-slate-100">
                {excelFile ? "Change Excel file" : "Upload Excel file"}
              </span>
              <span className="mt-2 text-sm text-slate-400">
                Accepted formats: .xlsx, .xls, .csv
              </span>
            </label>

            <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-900/70 p-4">
              <p className="text-sm font-medium text-slate-200">Selected file</p>
              <p className="mt-1 text-sm text-slate-400">
                {excelFile ? excelFile.name : "No file selected yet."}
              </p>
            </div>

            <button
              type="button"
              onClick={handleAnalyze}
              disabled={!excelFile || isLoading}
              className="mt-6 w-full rounded-2xl bg-cyan-500 px-4 py-3 font-semibold text-slate-950 transition hover:bg-cyan-400 disabled:cursor-not-allowed disabled:bg-slate-700 disabled:text-slate-400"
            >
              {isLoading ? "Analyzing..." : "Generate chart"}
            </button>

            {error ? (
              <p className="mt-4 rounded-2xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-300">
                {error}
              </p>
            ) : null}
          </div>

          <div className="rounded-3xl border border-slate-800 bg-slate-950/70 p-6">
            {stats ? (
              <>
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-xl font-semibold">Tag breakdown</h2>
                    <p className="mt-1 text-sm text-slate-400">
                      {stats.total} rows analyzed
                    </p>
                  </div>
                </div>

                <div className="mt-8 space-y-5">
                  {chartData.map((item) => (
                    <div key={item.label}>
                      <div className="mb-2 flex items-center justify-between text-sm">
                        <span className="text-slate-300">{item.label}</span>
                        <span className="font-medium text-slate-100">{item.value}</span>
                      </div>
                      <div className="h-3 w-full overflow-hidden rounded-full bg-slate-800">
                        <div
                          className="h-full rounded-full"
                          style={{ width: `${(item.value / maxValue) * 100}%`, backgroundColor: item.color }}
                        />
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-8">
                  <h3 className="text-lg font-semibold text-slate-100">By P&amp;ID</h3>
                  <div className="mt-4 space-y-3">
                    {(stats.by_pid ?? []).length > 0 ? (
                      (stats.by_pid ?? []).map((entry) => (
                        <div key={entry.pid} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4">
                          <div className="flex items-center justify-between gap-3">
                            <span className="font-medium text-slate-100">{entry.pid || "Unknown"}</span>
                            <span className="text-sm text-slate-400">{entry.total} items</span>
                          </div>
                          <div className="mt-3 grid gap-2 sm:grid-cols-3">
                            <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-sm">
                              <div className="text-emerald-200">Instruments</div>
                              <div className="mt-1 font-semibold text-white">{entry.counts.Instrument}</div>
                            </div>
                            <div className="rounded-xl border border-sky-500/20 bg-sky-500/10 p-3 text-sm">
                              <div className="text-sky-200">Equipment</div>
                              <div className="mt-1 font-semibold text-white">{entry.counts.Equipment}</div>
                            </div>
                            <div className="rounded-xl border border-violet-500/20 bg-violet-500/10 p-3 text-sm">
                              <div className="text-violet-200">Pipe-runs</div>
                              <div className="mt-1 font-semibold text-white">{entry.counts["Pipe-run"]}</div>
                            </div>
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="rounded-2xl border border-dashed border-slate-800 bg-slate-900/60 p-4 text-sm text-slate-400">
                        No P&amp;ID-specific breakdown was returned for this workbook.
                      </div>
                    )}
                  </div>
                </div>
              </>
            ) : (
              <div className="flex h-full min-h-70 items-center justify-center rounded-2xl border border-dashed border-slate-800 bg-slate-900/60 p-6 text-center text-sm text-slate-400">
                Upload a workbook to see the chart here.
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
